/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal.View;

/**
 *
 * @author vinic
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelValorTotal = new javax.swing.JTextField();
        botaoGeraTicket = new javax.swing.JButton();
        labelFuncionario = new javax.swing.JLabel();
        panelLog = new javax.swing.JScrollPane();
        entradaCarro = new javax.swing.JTextArea();
        labelDia = new javax.swing.JLabel();
        labelVagasDisponiveis = new javax.swing.JTextField();
        botaoSair = new javax.swing.JToggleButton();
        labelVagasOcupadas = new javax.swing.JTextField();
        paneMenu = new javax.swing.JTabbedPane();
        panelGuiaCadastros = new javax.swing.JPanel();
        botaoCadVeiculo = new javax.swing.JButton();
        BotaoCadCliente = new javax.swing.JButton();
        botaoCadVagas = new javax.swing.JButton();
        cadValorHora = new javax.swing.JButton();
        panelGuiaHistoricoValores = new javax.swing.JPanel();
        panelHistorico = new javax.swing.JScrollPane();
        caixaHistoricoValor = new javax.swing.JTextArea();
        botaoAtualizarValorHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelValorTotal.setEditable(false);
        labelValorTotal.setBackground(new java.awt.Color(255, 255, 255));
        labelValorTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelValorTotal.setText("VALOR TOTAL R$");
        labelValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelValorTotalActionPerformed(evt);
            }
        });

        botaoGeraTicket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoGeraTicket.setText("Gerar Ticket");
        botaoGeraTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGeraTicketActionPerformed(evt);
            }
        });

        labelFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFuncionario.setText("Funcionário");

        entradaCarro.setEditable(false);
        entradaCarro.setBackground(new java.awt.Color(230, 230, 254));
        entradaCarro.setColumns(20);
        entradaCarro.setRows(5);
        panelLog.setViewportView(entradaCarro);

        labelDia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDia.setText("DATA");

        labelVagasDisponiveis.setEditable(false);
        labelVagasDisponiveis.setBackground(new java.awt.Color(102, 255, 51));
        labelVagasDisponiveis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVagasDisponiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelVagasDisponiveis.setText("Vagas Disponiveis");

        botaoSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 0, 0));
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        labelVagasOcupadas.setEditable(false);
        labelVagasOcupadas.setBackground(new java.awt.Color(255, 0, 0));
        labelVagasOcupadas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVagasOcupadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelVagasOcupadas.setText("Vagas Ocupadas");

        paneMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoCadVeiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCadVeiculo.setText("Cadastrar Veiculo");
        botaoCadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadVeiculoActionPerformed(evt);
            }
        });

        BotaoCadCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotaoCadCliente.setText("Cadastrar Cliente");
        BotaoCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadClienteActionPerformed(evt);
            }
        });

        botaoCadVagas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCadVagas.setText("Cadastrar Vagas");
        botaoCadVagas.setMaximumSize(new java.awt.Dimension(141, 25));
        botaoCadVagas.setMinimumSize(new java.awt.Dimension(141, 25));
        botaoCadVagas.setPreferredSize(new java.awt.Dimension(141, 25));
        botaoCadVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadVagasActionPerformed(evt);
            }
        });

        cadValorHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadValorHora.setText("Cadastrar Valor/Hora");
        cadValorHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadValorHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuiaCadastrosLayout = new javax.swing.GroupLayout(panelGuiaCadastros);
        panelGuiaCadastros.setLayout(panelGuiaCadastrosLayout);
        panelGuiaCadastrosLayout.setHorizontalGroup(
            panelGuiaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuiaCadastrosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelGuiaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelGuiaCadastrosLayout.setVerticalGroup(
            panelGuiaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuiaCadastrosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(botaoCadVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BotaoCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(botaoCadVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(cadValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        paneMenu.addTab("CADASTROS", panelGuiaCadastros);

        caixaHistoricoValor.setEditable(false);
        caixaHistoricoValor.setColumns(20);
        caixaHistoricoValor.setRows(5);
        panelHistorico.setViewportView(caixaHistoricoValor);

        botaoAtualizarValorHistorico.setText("ATUALIZAR HISTORICO");
        botaoAtualizarValorHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarValorHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuiaHistoricoValoresLayout = new javax.swing.GroupLayout(panelGuiaHistoricoValores);
        panelGuiaHistoricoValores.setLayout(panelGuiaHistoricoValoresLayout);
        panelGuiaHistoricoValoresLayout.setHorizontalGroup(
            panelGuiaHistoricoValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuiaHistoricoValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuiaHistoricoValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtualizarValorHistorico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGuiaHistoricoValoresLayout.setVerticalGroup(
            panelGuiaHistoricoValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuiaHistoricoValoresLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(botaoAtualizarValorHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paneMenu.addTab("HISTORICO VALORES", panelGuiaHistoricoValores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVagasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelVagasDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(botaoGeraTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelLog, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoSair)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoSair)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFuncionario)
                    .addComponent(labelDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelVagasDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelVagasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(botaoGeraTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelLog))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoGeraTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGeraTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoGeraTicketActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoAtualizarValorHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarValorHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAtualizarValorHistoricoActionPerformed

    private void cadValorHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadValorHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadValorHoraActionPerformed

    private void botaoCadVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadVagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadVagasActionPerformed

    private void BotaoCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadClienteActionPerformed

    private void botaoCadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadVeiculoActionPerformed

    private void labelValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelValorTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadCliente;
    private javax.swing.JButton botaoAtualizarValorHistorico;
    private javax.swing.JButton botaoCadVagas;
    private javax.swing.JButton botaoCadVeiculo;
    private javax.swing.JButton botaoGeraTicket;
    private javax.swing.JToggleButton botaoSair;
    private javax.swing.JButton cadValorHora;
    private javax.swing.JTextArea caixaHistoricoValor;
    private javax.swing.JTextArea entradaCarro;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelFuncionario;
    private javax.swing.JTextField labelVagasDisponiveis;
    private javax.swing.JTextField labelVagasOcupadas;
    private javax.swing.JTextField labelValorTotal;
    private javax.swing.JTabbedPane paneMenu;
    private javax.swing.JPanel panelGuiaCadastros;
    private javax.swing.JPanel panelGuiaHistoricoValores;
    private javax.swing.JScrollPane panelHistorico;
    private javax.swing.JScrollPane panelLog;
    // End of variables declaration//GEN-END:variables
}
