
package Principal.View;

import estacionamento.cadastros.cadastroUsuario;

/**
 *
 * @author Débora
 */
public class sistemaNovo extends javax.swing.JFrame {

    /**
     * Creates new form sistemaInicio
     */
    public sistemaNovo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botaoLogin = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(535, 357));
        setResizable(false);
        setSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(null);

        botaoLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoLogin.setText("LOGIN");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(botaoLogin);
        botaoLogin.setBounds(260, 80, 210, 50);

        botaoCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrar);
        botaoCadastrar.setBounds(260, 190, 210, 50);

        icon.setIcon(new javax.swing.ImageIcon("/src/Principal/sistema/Imagens/carro.png")); // NOI18N
        icon.setLabelFor(icon);
        getContentPane().add(icon);
        icon.setBounds(20, -70, 210, 390);
        
        pack();
        setLocationRelativeTo(null);
    }
    
    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {        
        ViewLogin login = new ViewLogin();
        login.setVisible(true);
        dispose();
    }

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {    
        ViewFuncionario cadastro = new ViewFuncionario();
        cadastro.setVisible(true);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistemaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistemaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistemaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistemaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistemaNovo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel icon;
    // End of variables declaration//GEN-END:variables
}
